### ISSUE TITLE
not really an issue

### ISSUE THREAD

**Issue by IIIdefconIII** [crclayton/custom-cortana-commands-template#3]
Hi if have been searching for two years for a good home automation system, this can be a reall hot add for me. The basic script i have been tested it and it works neat!

I just want 1 thing and thats implent my code to this to run tasks...

Im not a good writer and also this code took me ages to get it running could you give me one example how i can implent this in youre cortanafunctions.cs

            {"OpenFile", (Action)(async () => {
                StorageFile file = await Package.Current.InstalledLocation.GetFileAsync(@"Test.txt");
                await Launcher.LaunchFileAsync(file);
            })},

mycode:

        private void WallLightsBright_Click(object sender, EventArgs e)
        {
            Process process = new Process();
            // Configure the process using the StartInfo properties.
            process.StartInfo.FileName = "C:\\Program Files (x86)\\Home Control\\plink.exe";
            process.StartInfo.Arguments = "******@127.0.0.1/home/iiidefconiii/HarmonyHubControl/HarmonyHubControl ********@gmail.com passwd issue_device_command 42458302 L05";
            process.StartInfo.WindowStyle = ProcessWindowStyle.Minimized;
            process.Start();
            process.WaitForExit();// Waits here for the process to exit.
        }

that code is currently running when i click a button. i really really like to have this piece of code working with cortane, is it even possible?

Thank You much for this great custom definitions

**Comment by crclayton** [comment]
According to this [GitHub Issue][1], SSH.NET supports UAP 10/UWP as of **SSH.NET 2016.0.0-beta1**, so you should be able to use that instead of doing it with plink and the command line, which can't be done in a UWP app. 

You can download it here: https://www.nuget.org/packages/SSH.NET

Then use it doing something like: 

    using (var client = new SshClient("hostnameOrIp", "username", "password"))
    {
        client.Connect();
        client.RunCommand("...");
        client.Disconnect();
    }


  [1]: https://github.com/sshnet/SSH.NET/issues/4

I haven't looked into it much further, but if you get it working then post it back here and I'll include SSH as one of the examples in the template. Good luck!


  [1]: https://github.com/sshnet/SSH.NET/issues/4

**Comment by IIIdefconIII** [comment]
i installed it weith the given instruction but unfortanly when i set that code im getting the following error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'SshClient' could not be found (are you missing a using directive or an assembly reference?)	Home Control	D:\localdoc\Visual Studio 2015\Projects\Home Control - systemtray\Home Control\Form1.cs	526	Active

im googlen, seacrhing and asking around but man this is hard stuff for me

**Comment by IIIdefconIII** [comment]
ok so go tit working yeah installed the lib and added:

using Renci;
using Renci.SshNet;
using Renci.SshNet.NetConf;
using Renci.SshNet.Common;
using Renci.SshNet.Channels;
using Renci.SshNet.Compression;
using Renci.SshNet.Sftp;
using Renci.SshNet.Security;
using Renci.SshNet.Messages;

still narrowing down which one i dont need.

and this is the actual code now:

        private void button6_Click_1(object sender, EventArgs e)
        {
            using (var client = new SshClient("10.19.1.7", "username", "pwd"))
            {
                client.Connect();
                client.RunCommand("/home/iiidefconiii/HarmonyHubControl/HarmonyHubControl *****@gmail.com ***** 10.19.1.8  issue_device_command 42458302 'Light6'");
                client.Disconnect();
            }
        }

**Comment by crclayton** [comment]
Awesome! Glad to help.

**Comment by IIIdefconIII** [comment]
could you let me know when you have enabled an ssh in the preview file? so i can put that code in there would be awesome

**Comment by ghost** [comment]
Is there any such workaround for Windows OS?
